# Generated by Django 5.1.5 on 2025-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healix", "0003_doctor_phd_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
