services:
  # Backend Service
  - type: web
    name: healix_backend
    env: python
    buildCommand: cd medical_booking && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd medical_booking && gunicorn medical_booking.wsgi:application
    staticPublishPath: ./medical_booking/staticfiles
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: healix_db
          property: connectionString
      - key: DATABASE_NAME
        fromDatabase:
          name: healix_db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: healix_db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: healix_db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: healix_db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: healix_db
          property: port
      - key: PYTHON_VERSION
        value: 3.11.0
    dependencies:
      - name: healix_db

  # Frontend Service
  - type: web
    name: Healix
    env: node
    buildCommand: >
      cd frontend &&
      npm cache clean --force &&
      rm -rf node_modules .next package-lock.json &&
      npm install typescript@5.3.3 &&
      npm install @types/react@18.2.55 @types/node@20.11.17 &&
      npm install &&
      npm install --save-dev @types/react-dom@18.2.19 &&
      npm run build
    startCommand: cd frontend && npm start
    staticPublishPath: ./frontend/public
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://healix-backend.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: SKIP_TYPE_CHECK
        value: "true"

databases:
  - name: healix_db
    databaseName: healix
    user: healix
    plan: pro
    ipAllowList: []