# Generated by Django 5.1.6 on 2025-03-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patientprofile_age_customuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
