# Generated by Django 4.2.20 on 2025-04-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_verified'),
        ('accounts', '0003_patientprofile_phone_number'),
        ('accounts', '0004_alter_appointment_status'),
    ]

    operations = [
    ]
