# Generated by Django 5.1.6 on 2025-04-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_phone_number'),
        ('accounts', '0004_alter_appointment_status'),
    ]

    operations = [
    ]
