# Generated by Django 5.1.6 on 2025-04-05 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20250403_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_datetime'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_license',
            field=models.FileField(default=django.utils.timezone.now, upload_to='licenses/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='office_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='office_number',
            field=models.CharField(default=11111, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(default=1111111, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificate',
            field=models.FileField(default=0, upload_to='certificates/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
