# Generated by Django 5.1.6 on 2025-04-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appointment_options_and_more'),
        ('accounts', '0007_patientprofile_phone_number'),
    ]

    operations = [
    ]
