# Generated by Django 5.1.6 on 2025-04-23 06:54

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AddField(
            model_name='appointment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='appointment_documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='accounts.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='appointment_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(default='No bio provided'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='education',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license',
            field=models.FileField(blank=True, null=True, upload_to='medical_licenses/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='office_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='office_hours_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='office_hours_start',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='office_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.doctor_profile_picture_path),
        ),
    ]
