# Generated by Django 5.1.6 on 2025-04-21 21:26

from django.db import migrations, models

def make_license_numbers_unique(apps, schema_editor):
    DoctorProfile = apps.get_model('accounts', 'DoctorProfile')
    # Set all existing license numbers to None
    DoctorProfile.objects.all().update(license_number=None)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_appointment_options_appointment_document_and_more'),
    ]

    operations = [
        migrations.RunPython(make_license_numbers_unique),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
