# Generated by Django 5.1.6 on 2025-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_appointment_options_appointment_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
